services:
  - type: web
    name: catalogo-toolcrib-backend
    env: node
    region: oregon
    plan: free

    buildCommand: "npm install"
    startCommand: "npm start"

    envVars:
      - key: DB_USER
        value: "postgres"

      - key: DB_HOST
        value: "dpg-render"   # <-- ESTA se remplaza cuando tengas la base de datos creada en Render

      - key: DB_NAME
        value: "CatalogoTOOLCRIB"

      - key: DB_PASSWORD
        value: "tecsanpedro"

      - key: DB_PORT
        value: "5432"

      - key: PORT
        value: "3000"

      - key: JWT_SECRET
        value: "TOOL1"

      - key: MASTER_KEY
        value: "TOOLCRIB1"
